interval: 5
flush_interval: 10
max_buffer_size: 5000        # Maximum number of entries to buffer if Redis is unavailable
warn_on_buffer: true
hostname: ''

debug: true
once: false

inputs:
  # - linux_cpu
  # - linux_mem
  # - linux_disk
  # - linux_io
  # - linux_net
  # - macos_cpu
  # - macos_mem
  # - macos_disk
  # - macos_io
  # - macos_net
  # - docker:
  #     endpoint: "unix:///var/run/docker.sock"
  #     gather_services: false
  #     swarm_enabled: false
  #     container_name_include: []
  #     container_name_exclude: []
  #     container_state_include: []
  #     container_state_exclude: []
  #     docker_label_include: []
  #     docker_label_exclude: []
  #     tag_env: ["JAVA_HOME", "HEAP_SIZE"]
  #     timeout: 5
  # - syslog:
  #     server: "tcp://127.0.0.1:5514"
  #     tls_cert: ""
  #     tls_key: ""
  #     socket_mode: ""
  #     max_connections: 0
  #     read_timeout: 0
  #     read_buffer_size: "64KiB"
  #     keep_alive_period: "5m"
  #     content_encoding: "identity"
  #     max_decompression_size: "500MB"
  #     framing: "octet-counting"
  #     trailer: "LF"
  #     best_effort: false
  #     syslog_standard: "RFC5424"
  #     sdparam_separator: "_"
  # - redis:
  #     host: "127.0.0.1"
  #     port: 6379
  #     password: ""
  #     db: 0
  # - mariadb:
  #     host: "127.0.0.1"
  #     port: 3306
  #     user: "monitor"
  #     password: "testpass"
  #     metrics:
  #       - Threads_connected
  #       - Connections
  #       - Uptime
  #       - Questions
  # - exec:
  #     commands:
  #       - "python3 /opt/scripts/report_temp.py"
  #     environment:
  #       - "ENV=production"
  #       - "PATH=/usr/local/bin:/usr/bin"
  #     timeout: 5
  #     data_format: "metrics"
  #     ignore_error: false
  - postgres:
      host: "127.0.0.1"
      port: 5432
      user: "monitor"
      password: "testpass"
      dbname: "postgres"
      # Optional: define custom queries to override default pg_stat_database
      # queries:
      #   - name: "connections"
      #     sql: "SELECT COUNT(*) FROM pg_stat_activity WHERE datname = current_database();"
      #   - name: "uptime"
      #     sql: "SELECT EXTRACT(EPOCH FROM now() - pg_postmaster_start_time())::bigint;"

outputs:
  - redistimeseries:
      host: atila.taild1b8e.ts.net
      port: 6379
      retention: 1y
  - redissearch:
      host: atila.taild1b8e.ts.net
      port: 6379
      index: "logs_idx"
      key_prefix: "log:"
      # Example proxy configuration for Redis outputs:
      # socks5_proxy: "socks5://username:password@127.0.0.1:1080"
      # socks4_proxy: "socks4://127.0.0.1:1080"
      # http_proxy: "http://username:password@proxy.example.com:8080"