interval: 10
retention: 86400000  # 1 day in milliseconds
hostname: ''
debug: true
once: false

inputs:
  - linux_cpu
  - linux_mem
  - linux_disk
  - linux_io
  - linux_net
  # - macos_cpu
  # - macos_mem
  # - macos_disk
  # - macos_io
  # - macos_net
  - docker:
      endpoint: "unix:///var/run/docker.sock"
      gather_services: false
      swarm_enabled: false
      container_name_include: []
      container_name_exclude: []
      container_state_include: []
      container_state_exclude: []
      docker_label_include: []
      docker_label_exclude: []
      tag_env: ["JAVA_HOME", "HEAP_SIZE"]
      timeout: 5

outputs:
  - redistimeseries:
      host: atila.taild1b8e.ts.net
      port: 6379